import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <title>Jake Shankman | Portfolio</title>
      <link rel="icon" href="favicon.ico" sizes="any"/>
    </head>
    <body>{children}</body>
    </html>
  );
}
